# This builds external data and writes it to Cloud Storage if the site passes a
# basic build. The workflow has a timeout of 900 seconds (15 minutes) to prevent
# infinite loops or other issues that could cause the workflow to run indefinitely.

timeout: 900s # Set the timeout for the entire workflow to 15 minutes

steps:  # An array of steps that define the tasks to be executed in the workflow
  - name: node:16.14.2  # Use the Node.js 16.14.2 container image for this step
    id: 'Install dependencies'  # Assign the step an ID for referencing later
    entrypoint: npm  # Use npm as the entrypoint for the container
    args: ['ci']  # Run the 'ci' script defined in the package.json file

  - name: node:16.14.2
    id: 'Configure secrets'
    entrypoint: npm
    args: ['run', 'cloud-secrets']
    env:  # Set environment variables for this step
      - 'NODE_ENV=production'

  - name: node:16.14.2
    id: 'Build external data'
    entrypoint: npm
    args: ['run', 'build-external']
    env:
      - 'NODE_ENV=production'

  - name: node:16.14.2
    id: 'Create .eleventyignore file'
    entrypoint: npm
    args: ['run', 'ignore']
    env:
      - 'ELEVENTY_IGNORE_NACL=true'  # Ignore .nacl files when building Eleventy

  - name: node:16.14.2
    id: 'Build eleventy in dev mode to confirm'
    entrypoint: npm
    args: ['run', 'eleventy']
    # This does NOT set `NODE_ENV=production`, as we don't need the full build.

  - name: 'gcr.io/cloud-builders/gcloud'  # Use the Google Cloud SDK builder container image
    id: 'Synchronize content to external-dcc-data bucket
